djangolikesproj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    #path('rating/<str:location_name>/', location_rating, name='location_rating'),
    path('ratings/', include('ratings.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ratings/urls.py
from django.urls import path
from . import views

app_name = 'ratings'

urlpatterns = [ 
    path('<str:location_name>', views.location_rating, name='location_rating'),
    path('<str:location_name>/add_rating', views.add_rating, name='add_rating')
]

ratings/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from colorful.fields import RGBColorField

# Create your models here.
class Location(models.Model):
    id = models.AutoField(primary_key=True)
    location_name = models.CharField('Местоположение', max_length=50)
    location_link = models.CharField('Ссылка на страницу', max_length=200, blank=True, null=True, editable=False)
    location_header = models.CharField('Заголовок', max_length=100, null=True)
    location_header_fs = models.IntegerField(default=30)
    header_color = RGBColorField('Цвет текста', null=True)
    main_image = models.ImageField(upload_to='location_images/', null=True)
    like_image = models.ImageField(upload_to='location_images/', blank=True, null=True)
    dislike_image = models.ImageField(upload_to='location_images/', blank=True, null=True)

    def __str__(self):
        return self.location_name
    def save(self, *args, **kwargs):
        if not self.location_link:
            self.location_link = reverse('ratings:location_rating', args=[self.location_name])
        super().save(*args, **kwargs)
    class Meta:
        verbose_name = "Местоположение"
        verbose_name_plural = "Местоположения"

class Rating(models.Model):
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    like = models.BooleanField()
    dislike = models.BooleanField()

    def __str__(self):
        date_formatted = self.date_created.strftime("%d.%m.%Y %H:%M")
        result_formatted = "Лайк" if self.like else "Дизлайк"
        return f"{result_formatted} {date_formatted}"
        #return f"Оценка {self.location.location_name} ({date_formatted})"

    class Meta:
        verbose_name = "Оценка"
        verbose_name_plural = "Оценки"

ratings/views.py
from django.shortcuts import render, get_object_or_404
from .models import Location, Rating
from django.http import HttpResponseRedirect
from django.urls import reverse

def location_rating(request, location_name):
    location = get_object_or_404(Location, location_name=location_name)
    ratings = Rating.objects.filter(location=location)

    context = {
        'location': location,
        'ratings': ratings,
    }
    return render(request, 'ratings/location_rating.html', context)

def add_rating(request, location_name):
    location = get_object_or_404(Location, location_name=location_name)

    if request.method == 'POST':
        action = request.POST.get('action')

        if action == 'like':
            Rating.objects.create(location=location, like=True, dislike=False)
        elif action == 'dislike':
            Rating.objects.create(location=location, like=False, dislike=True)

        return HttpResponseRedirect(reverse('ratings:location_rating', args=[location_name]))

    context = {
        'location': location
    }
    return render(request, 'ratings/location_rating.html', context)

ratings/templates/ratings/location_rating.html
<!DOCTYPE html>
<html>
<head>
  <title>Location Rating</title>
  <style>
    body {
      background: url('{{ location.main_image.url }}') no-repeat center center fixed;
      background-size: cover;
    }
    .container {
      max-width: 600px;
      margin: 0 auto;
      padding: 20px;
      text-align: center;
    }
    h1 {
      color: {{ location.header_color }};
      font-size: {{ location.location_header_fs }}px;
      margin-bottom: 20px;

    }
    .rating-buttons {
      margin-top: 45%;
    }
    .rating-buttons button {
      display: inline-block;
      background-color: transparent;
      border: none;
      padding: 0;
      margin-right: 10px;
      cursor: pointer;
    }
    .like-button {
      background-image: url('{{ location.like_image.url }}');
      background-size: contain;
      width: 50px;
      height: 50px;
    }
    .dislike-button {
      background-image: url('{{ location.dislike_image.url }}');
      background-size: contain;
      width: 50px;
      height: 50px;
    }
  </style>
</head>
<body>

  <div class="container">
    <h1>{{ location.location_header }}</h1>
    <div class="rating-buttons">
      <form method="POST" action="{% url 'ratings:add_rating' location.location_name %}">
        {% csrf_token %}
        <button type="submit" name="action" value="like" class="like-button"></button>
        <button type="submit" name="action" value="dislike" class="dislike-button"></button>
      </form>
    </div>
  </div>
</body>
</html>